name: 'azure-cd for HW3'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.0
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.0
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"
        
        
  build:
    env:
      AZURE_WEBAPP_NAME: HW3my-app
      
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip 
          pip install -U Flask

    - name: Archive Application with Dependencies
      run: |
        mkdir -p function_package 
        cp HW3my-app.py function_package/
        zip -r function_package2.zip function_package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: function_package2
        path: function_package2.zip

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: function_package2
        path: function_package.zip

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: function_package2.zip
 
