name: HW3 app Buid and Deploy on Azure

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    AZURE_WEBAPP_NAME: HW3my-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
            python -m venv venv
            source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -U Flask

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
            name: python-app
            path: |
              .
              !venv/
        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}